[monitor:///mnt/bunkerlogs/access.log]
sourcetype = bunkerweb:access
index = bunkerweb-access-logs

[monitor:///mnt/bunkerlogs/error.log]
sourcetype = bunkerweb:error
index = bunkerweb-error-logs

[monitor:///mnt/bunkerlogs/modsec_audit.log]
sourcetype = bunkerweb:modsec
index = bunkerweb-modsec-logs
