# ----- Bunkerweb -----
[SERVICE]
    Flush              5
    Daemon             Off
    Log_Level          info
    Parsers_File       parsers.conf
    Buffer_Chunk_Size  1M
    Buffer_Max_Size    2M

[INPUT]
    Name              tail
    Path              /fluentbit-logs/access.log
    Tag               bunker.access
    Refresh_Interval  5
    Read_From_Head    true
    Parser            bunkerweb

[FILTER]
    Name              record_modifier
    Match             bunker.*
    Record            hostname bunkerweb

[OUTPUT]
    Name              splunk
    Match             bunker.*
    Host              172.20.0.100
    Port              8088
    TLS               On
    TLS.Verify        Off
    Splunk_Token      ${SPLUNK_HEC_BUNKERTOKEN}
    Splunk_Send_Raw   Off
    Event_Key         $event
    Event_Host        bunkerweb
    Event_Sourcetype  bunkerweb_access
    Event_Index       main


# [OUTPUT]
#     Name stdout
#     Match *
#     Format json


# ----- FAIL2BAN -----
[INPUT]
    Name              tail
    Path              /fail2ban/fail2ban.log
    Tag               fail2ban.logs
    Read_From_Head    true
    Refresh_Interval  5
    DB                off
    Parser            fail2ban
    Log_Level         debug


[FILTER]
    Name    record_modifier
    Match   fail2ban.*
    Record  hostname fail2banhost

[OUTPUT]
    Name              splunk
    Match             fail2ban.*
    Host              172.20.0.100
    Port              8088
    TLS               On
    TLS.Verify        Off
    Splunk_Token      ${SPLUNK_HEC_FAIL2BANTOKEN}
    Splunk_Send_Raw   On
    Event_Host        fail2banhost
    Event_Sourcetype  fail2ban_log
    Event_Index       security


# [OUTPUT]
#     Name  stdout
#     Match fail2ban.*