[PARSER]
    Name   bunkerweb
    Format regex
    Regex  ^(?<remote_host>\S+) (?<client_ip>\S+) \S+ \S+ \[(?<time>[^\]]+)\] "(?<method>\S+)? (?<request>[^\"]+)? (?<protocol>[^"]+)?" (?<status>\d{3}) (?<bytes_sent>\d+) "(?<referrer>[^\"]*)" "(?<user_agent>[^\"]*)"
    Time_Key    time
    Time_Format %d/%b/%Y:%H:%M:%S %z
    Time_Keep   On
