# HTTP Server
server {
    listen 80;
    listen [::]:80;
    server_name crumbly.mooo.com;

    # Document Root
    root /var/www/html;
    index index.php index.html index.htm;

    access_log /dev/stdout main;
    error_log /dev/stderr warn;

    location = /robots.txt {
        root /var/www/html;
        access_log off;
        log_not_found off;
    }

    location / {
        try_files $uri $uri/ /index.php$is_args$args;
    }

    
    # PHP-FPM Configuration
    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass php:9000;  # This is correct since your Dockerfile is php:8.2-fpm
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }

    # Deny access to hidden files
    location ~ /\. {
        deny all;
    }
}

# HTTPS Server
# server {
#     listen 443 ssl;
#     listen [::]:443 ssl;
#     server_name crumbly.mooo.com;
    
#     # SSL Certificate paths (Let's Encrypt)
#     ssl_certificate /etc/letsencrypt/live/crumbly.mooo.com/fullchain.pem;
#     ssl_certificate_key /etc/letsencrypt/live/crumbly.mooo.com/privkey.pem;
    
#     # SSL Configuration
#     ssl_protocols TLSv1.2 TLSv1.3;
#     ssl_prefer_server_ciphers on;
#     ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;
    
#     # Document Root
#     root /var/www/html;
#     index index.php index.html index.htm;

#     # Default Location
#     location / {
#         try_files $uri $uri/ /index.php?$query_string;
#     }
    
#     # PHP-FPM Configuration
#     location ~ \.php$ {
#         try_files $uri =404;
#         fastcgi_split_path_info ^(.+\.php)(/.+)$;
#         fastcgi_pass php:9000;  # This is correct since your Dockerfile is php:8.2-fpm
#         fastcgi_index index.php;
#         include fastcgi_params;
#         fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
#         fastcgi_param PATH_INFO $fastcgi_path_info;
#     }
    
#     # Deny access to hidden files
#     location ~ /\. {
#         deny all;
#     }
# }