name: PHPUnit Automated Unit Testing

on: [push, pull_request]

jobs:
  phpunit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, json, curl

      - name: Install PHP dependencies
        run: composer install --no-progress --prefer-dist

      - name: Run PHPUnit tests
        run: ./vendor/bin/phpunit --testdox
